# Site settings
title: Southampton University Fencing Club
email: webmaster@sotonfencing.co.uk
description:
    We are a student-run Fencing club based at the University of Southampton,
    UK. We provide coaching for all ability levels, and compete throughout the
    country.
copyright: "&copy; 2014 Southampton University Fencing Club TODO:license"
baseurl: ""
url: "http://sotonfencing.co.uk/"

# Build settings
markdown: kramdown
permalink: pretty
exclude:
    - node_modules
