# Site settings
title: Southampton University Fencing Club
email: fencing@soton.ac.uk
webmaster_email: webmaster@sotonfencing.co.uk
description:
    We are a student-run Fencing club based at the University of Southampton,
    UK. We provide coaching for all ability levels, and compete throughout the
    country.
copyright: "&copy; 2014 Southampton University Fencing Club"
baseurl: ""
url: "http://www.sotonfencing.co.uk"

# Links
links:
    susu_group: "https://susu.org/groups/fencing"
    facebook_group: "https://facebook.com/groups/sotonfencing/"

# Build settings
markdown: kramdown
permalink: pretty
exclude:
    - node_modules
